general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = niri msg action power-on-monitors
}

listener {
    timeout = 300 # 5 min
    on-timeout = brightnessctl --save set $(( $(brightnessctl get) / 3 ))
    on-resume = brightnessctl --restore
}

listener {
    timeout = 550 # 9.5 min
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600 # 10 min
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

listener {
    timeout = 1800 # 30 min
    on-timeout = systemctl suspend
}
